### ISSUE TITLE
Skeleton Hand to pass turn not there

### ISSUE THREAD

**Issue by CalciB** [Arackulele/GrimoraMod#209]
![image](https://github.com/Arackulele/GrimoraMod/assets/108853112/74e4349f-97a1-4753-ad6a-cf67c2d10131)
My mods
![image](https://github.com/Arackulele/GrimoraMod/assets/108853112/147a89e2-565d-4871-ac81-1f03dbcf4647)

**Comment by TweetzTM** [comment]
Same, no way to play the mod without the ability to end the turn..

**Comment by MrKristijan** [comment]
I experience the same issue, there is no way to play the mod without it. Hope it will get fixed sooner or later since I really want to play the mod.

**Comment by TweetzTM** [comment]
> I experience the same issue, there is no way to play the mod without it. Hope it will get fixed sooner or later since I really want to play the mod.


Alright, some friendly fella on the Grimora mod community Discord server helped me out, apparently this is a known issue caused by the game thinking you are currently located in the Act 1 tutorial, and there are 2 known ways to fix it;

1. Simply once, enter Act 2 in the chapter select. Just back out to the menu and re-enter the Grimora mod afterwards, thats it.

2. Install a mod called 'Unlock all'. Not sure what this does exactly cuz I didn't bother to research, but it sounded fun so I went with this option.


The hand (bell) just reappears upon entering the tabletop section after either selecting chapter or launching the game with the unlock all mod, have fun! :)

**Comment by Arackulele** [comment]
this isnt an actual bug, just an installation issue
