### ISSUE TITLE
Bell Not Working and Game Freeze

### ISSUE THREAD

**Issue by BDonutGLXY** [Arackulele/GrimoraMod#252]
During one of those battles with specific events, this one being the tidal one, the bell suddenly decided to not work no matter how much I clicked it, and leaving the game causes it to freeze on a black screen

The unity log seems to say something along the lines of "Object reference not set to an instance of an object", meaning something is trying to reference an object but it doesn't exist, perhaps a card that was killed by the waves before the game could do something with it?

I have a feeling its related to the frozen skeleton thing, as it happened every time the skeleton was freed from what I remember, the skeleton even stays on the board????

Whatever im no expert

**Comment by Andromeda606** [comment]
The same problem arose when I got the skeletal augmentation (I don't know what to call it exactly, I sacrificed my starting bone so that a skeleton would come out every 3 turns) after doing this, I couldn't click the bell in the game if the board was full. This happened when Grimora was in the last state in the boss battle and I closed the game. Very frustrating.

**Comment by keks307** [comment]
This will be fixed in the new update. The test version already has a working solution included.
