### ISSUE TITLE
Game chugs during battles

### ISSUE THREAD

**Issue by CainReval** [Arackulele/GrimoraMod#253]
I want to preface that Ive never run into issues with battles slowing the game down before. While on the board the game runs fine. But after a battle begins, the game slowly gets slower and slower until its only running about 1 frame a second. Could there be some sort of background processing thats happening that could be overloading the game?

**Comment by Arackulele** [comment]
There is no memory leak in grimoramod ( that i know of ) and there is a lot of processes running in the background but none that seriously impact game performance. If you can write in your computers specs that would be helpful to see. Keep in mind mods will always run worse than the original game due to technical reasons.
