### ISSUE TITLE
Wrong Gifts in Bard Eventpieces or Wrong item discryption

### ISSUE THREAD

**Issue by An4el** [Arackulele/GrimoraMod#265]
I got Mrs. Bomb's Remote in Bard Eventpieces and when I try to look up its descryption, it gives a wrong descryption.
By the way the items I can get in this event may be to cvariable, I got Bone Lord's Femur in another run of game.
![DZ~L@5KRW$J@LN 0S@~HT92](https://github.com/user-attachments/assets/2ed58810-a01b-4a12-a434-fa1ca8a5989d)

**Comment by Arackulele** [comment]
Gravebard node has an about 1% chance to give you an item from other acts ( with exceptions for ones that break the game ), so good luck on getting that. Now since grimoramod doesnt have a classic item rulebook it fails to load up the articles for those items and just displays the backup string ( which is for the bonelords horn ), ill make sure to change the backup string before the next update so grimora says something like "Im not sure how this ended up here"
